//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.WebPortal.WebMVC4.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cedar.WebPortal.WebMVC4.Resources.CommandResource", typeof(CommandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string Account_LogOn {
            get {
                return ResourceManager.GetString("Account_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Register.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        public static string Applicant_Create {
            get {
                return ResourceManager.GetString("Applicant_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant List.
        /// </summary>
        public static string Applicant_List {
            get {
                return ResourceManager.GetString("Applicant_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job opportunity.
        /// </summary>
        public static string Applicant_Opportunity {
            get {
                return ResourceManager.GetString("Applicant_Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Attachments.
        /// </summary>
        public static string ApplicantSalesShop_AsyncUpload {
            get {
                return ResourceManager.GetString("ApplicantSalesShop_AsyncUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicantSalesShops Registeration.
        /// </summary>
        public static string ApplicantSalesShop_Create {
            get {
                return ResourceManager.GetString("ApplicantSalesShop_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ApplicantSalesShops.
        /// </summary>
        public static string ApplicantSalesShop_ListAdmin {
            get {
                return ResourceManager.GetString("ApplicantSalesShop_ListAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Step.
        /// </summary>
        public static string ApplicantSalesShop_Success {
            get {
                return ResourceManager.GetString("ApplicantSalesShop_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment View.
        /// </summary>
        public static string Attachment_GetContents {
            get {
                return ResourceManager.GetString("Attachment_GetContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment_Index {
            get {
                return ResourceManager.GetString("Attachment_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input symbols.
        /// </summary>
        public static string Captcha_InputSymbol {
            get {
                return ResourceManager.GetString("Captcha_InputSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Captcha_Refresh {
            get {
                return ResourceManager.GetString("Captcha_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Attachments.
        /// </summary>
        public static string Company_AsyncUpload {
            get {
                return ResourceManager.GetString("Company_AsyncUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Affair.
        /// </summary>
        public static string Company_Create {
            get {
                return ResourceManager.GetString("Company_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Affair.
        /// </summary>
        public static string Company_Intro {
            get {
                return ResourceManager.GetString("Company_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company List.
        /// </summary>
        public static string Company_List {
            get {
                return ResourceManager.GetString("Company_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        public static string Company_ProductList {
            get {
                return ResourceManager.GetString("Company_ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Step.
        /// </summary>
        public static string Company_Success {
            get {
                return ResourceManager.GetString("Company_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string CreateAndReady {
            get {
                return ResourceManager.GetString("CreateAndReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page Cannot Be Displayed.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Confirm.
        /// </summary>
        public static string Gallery_Confirm {
            get {
                return ResourceManager.GetString("Gallery_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery News.
        /// </summary>
        public static string Gallery_Create {
            get {
                return ResourceManager.GetString("Gallery_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Edit.
        /// </summary>
        public static string Gallery_Edit {
            get {
                return ResourceManager.GetString("Gallery_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery List.
        /// </summary>
        public static string Gallery_List {
            get {
                return ResourceManager.GetString("Gallery_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Home_AboutUs {
            get {
                return ResourceManager.GetString("Home_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Home_ContactUs {
            get {
                return ResourceManager.GetString("Home_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Home_FAQ {
            get {
                return ResourceManager.GetString("Home_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Home_ListPaginationGallery {
            get {
                return ResourceManager.GetString("Home_ListPaginationGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureGallery.
        /// </summary>
        public static string Home_PictureGallery {
            get {
                return ResourceManager.GetString("Home_PictureGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender.
        /// </summary>
        public static string Home_Tender {
            get {
                return ResourceManager.GetString("Home_Tender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3G.
        /// </summary>
        public static string Home_VAS {
            get {
                return ResourceManager.GetString("Home_VAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position List.
        /// </summary>
        public static string JobPosition_List {
            get {
                return ResourceManager.GetString("JobPosition_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Message_Create {
            get {
                return ResourceManager.GetString("Message_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message List.
        /// </summary>
        public static string Message_List {
            get {
                return ResourceManager.GetString("Message_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Confirm.
        /// </summary>
        public static string News_Confirm {
            get {
                return ResourceManager.GetString("News_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string News_Create {
            get {
                return ResourceManager.GetString("News_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Edit.
        /// </summary>
        public static string News_Edit {
            get {
                return ResourceManager.GetString("News_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News List.
        /// </summary>
        public static string News_List {
            get {
                return ResourceManager.GetString("News_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Prospect_Create {
            get {
                return ResourceManager.GetString("Prospect_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Prospect_Hold {
            get {
                return ResourceManager.GetString("Prospect_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information.
        /// </summary>
        public static string Prospect_Information {
            get {
                return ResourceManager.GetString("Prospect_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About preregistration.
        /// </summary>
        public static string Prospect_PreCreate {
            get {
                return ResourceManager.GetString("Prospect_PreCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Registration.
        /// </summary>
        public static string Prospect_RegisterTitle {
            get {
                return ResourceManager.GetString("Prospect_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Prospect_Search {
            get {
                return ResourceManager.GetString("Prospect_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string TenderApplication_Success {
            get {
                return ResourceManager.GetString("TenderApplication_Success", resourceCulture);
            }
        }
    }
}
