//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.WebPortal.WebMVC4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cedar.WebPortal.WebMVC4.Resources.CommandResource", typeof(CommandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string Account_LogOn {
            get {
                return ResourceManager.GetString("Account_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Register.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment View.
        /// </summary>
        public static string Attachment_GetContents {
            get {
                return ResourceManager.GetString("Attachment_GetContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment_Index {
            get {
                return ResourceManager.GetString("Attachment_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page Cannot Be Displayed.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Confirm.
        /// </summary>
        public static string News_Confirm {
            get {
                return ResourceManager.GetString("News_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string News_Create {
            get {
                return ResourceManager.GetString("News_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Edit.
        /// </summary>
        public static string News_Edit {
            get {
                return ResourceManager.GetString("News_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News List.
        /// </summary>
        public static string News_Index {
            get {
                return ResourceManager.GetString("News_Index", resourceCulture);
            }
        }
    }
}
