//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.WebPortal.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cedar.WebPortal.Domain.Resources.EntityResource", typeof(EntityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Advertisement.
        /// </summary>
        public static string AcquaintanceWay_InternetAdvertisement {
            get {
                return ResourceManager.GetString("AcquaintanceWay_InternetAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string AcquaintanceWay_Other {
            get {
                return ResourceManager.GetString("AcquaintanceWay_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Advertisement.
        /// </summary>
        public static string AcquaintanceWay_PaperAdvertisement {
            get {
                return ResourceManager.GetString("AcquaintanceWay_PaperAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string AcquaintanceWay_People {
            get {
                return ResourceManager.GetString("AcquaintanceWay_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Agency.
        /// </summary>
        public static string AcquaintanceWay_RecruitmentAgency {
            get {
                return ResourceManager.GetString("AcquaintanceWay_RecruitmentAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ave.
        /// </summary>
        public static string Address_Ave {
            get {
                return ResourceManager.GetString("Address_Ave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildingNo.
        /// </summary>
        public static string Address_BuildingNo {
            get {
                return ResourceManager.GetString("Address_BuildingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Address_Description {
            get {
                return ResourceManager.GetString("Address_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Address_Email {
            get {
                return ResourceManager.GetString("Address_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Address_Fax {
            get {
                return ResourceManager.GetString("Address_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Address_PostalCode {
            get {
                return ResourceManager.GetString("Address_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Address_Province {
            get {
                return ResourceManager.GetString("Address_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Address_Tel {
            get {
                return ResourceManager.GetString("Address_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelCode.
        /// </summary>
        public static string Address_TelCode {
            get {
                return ResourceManager.GetString("Address_TelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Address_Unit {
            get {
                return ResourceManager.GetString("Address_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcquaintanceWay.
        /// </summary>
        public static string Applicant_AcquaintanceWay {
            get {
                return ResourceManager.GetString("Applicant_AcquaintanceWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Applicant_Activities {
            get {
                return ResourceManager.GetString("Applicant_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Applicant_Address {
            get {
                return ResourceManager.GetString("Applicant_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationDate.
        /// </summary>
        public static string Applicant_ApplicationDate {
            get {
                return ResourceManager.GetString("Applicant_ApplicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Applicant_Attachment {
            get {
                return ResourceManager.GetString("Applicant_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string Applicant_BirthDate {
            get {
                return ResourceManager.GetString("Applicant_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood.
        /// </summary>
        public static string Applicant_Blood {
            get {
                return ResourceManager.GetString("Applicant_Blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Applicant_Certificates {
            get {
                return ResourceManager.GetString("Applicant_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildCount.
        /// </summary>
        public static string Applicant_ChildCount {
            get {
                return ResourceManager.GetString("Applicant_ChildCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractType.
        /// </summary>
        public static string Applicant_ContractType {
            get {
                return ResourceManager.GetString("Applicant_ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviction.
        /// </summary>
        public static string Applicant_Conviction {
            get {
                return ResourceManager.GetString("Applicant_Conviction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal Record.
        /// </summary>
        public static string Applicant_CriminalRecord {
            get {
                return ResourceManager.GetString("Applicant_CriminalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronic Disease.
        /// </summary>
        public static string Applicant_CronicDisease {
            get {
                return ResourceManager.GetString("Applicant_CronicDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronic Disease Type.
        /// </summary>
        public static string Applicant_CronicDiseaseType {
            get {
                return ResourceManager.GetString("Applicant_CronicDiseaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV File.
        /// </summary>
        public static string Applicant_CV {
            get {
                return ResourceManager.GetString("Applicant_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability.
        /// </summary>
        public static string Applicant_Disability {
            get {
                return ResourceManager.GetString("Applicant_Disability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationInfos.
        /// </summary>
        public static string Applicant_EducationInfos {
            get {
                return ResourceManager.GetString("Applicant_EducationInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        public static string Applicant_EMail {
            get {
                return ResourceManager.GetString("Applicant_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmeregencyTelNo.
        /// </summary>
        public static string Applicant_EmeregencyTelNo {
            get {
                return ResourceManager.GetString("Applicant_EmeregencyTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English CV File.
        /// </summary>
        public static string Applicant_EnglishCV {
            get {
                return ResourceManager.GetString("Applicant_EnglishCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errand Hours.
        /// </summary>
        public static string Applicant_ErrandDays {
            get {
                return ResourceManager.GetString("Applicant_ErrandDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errands.
        /// </summary>
        public static string Applicant_Errands {
            get {
                return ResourceManager.GetString("Applicant_Errands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrandTendency.
        /// </summary>
        public static string Applicant_ErrandTendency {
            get {
                return ResourceManager.GetString("Applicant_ErrandTendency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExFamilyName.
        /// </summary>
        public static string Applicant_ExFamilyName {
            get {
                return ResourceManager.GetString("Applicant_ExFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Salary Rls.
        /// </summary>
        public static string Applicant_ExpectedSalary {
            get {
                return ResourceManager.GetString("Applicant_ExpectedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeColor.
        /// </summary>
        public static string Applicant_EyeColor {
            get {
                return ResourceManager.GetString("Applicant_EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaceColor.
        /// </summary>
        public static string Applicant_FaceColor {
            get {
                return ResourceManager.GetString("Applicant_FaceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FatherName.
        /// </summary>
        public static string Applicant_FatherName {
            get {
                return ResourceManager.GetString("Applicant_FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string Applicant_FirstName {
            get {
                return ResourceManager.GetString("Applicant_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name in English.
        /// </summary>
        public static string Applicant_FirstNameInEnglish {
            get {
                return ResourceManager.GetString("Applicant_FirstNameInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followup Code.
        /// </summary>
        public static string Applicant_FollowupCode {
            get {
                return ResourceManager.GetString("Applicant_FollowupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Applicant_Gender {
            get {
                return ResourceManager.GetString("Applicant_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HabitationInfos.
        /// </summary>
        public static string Applicant_HabitationInfos {
            get {
                return ResourceManager.GetString("Applicant_HabitationInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Applicant_Height {
            get {
                return ResourceManager.GetString("Applicant_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HolidayNotWorkingReason.
        /// </summary>
        public static string Applicant_HolidayNotWorkingReason {
            get {
                return ResourceManager.GetString("Applicant_HolidayNotWorkingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HolidayWork.
        /// </summary>
        public static string Applicant_HolidayWork {
            get {
                return ResourceManager.GetString("Applicant_HolidayWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeTelNo.
        /// </summary>
        public static string Applicant_HomeTelNo {
            get {
                return ResourceManager.GetString("Applicant_HomeTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown.
        /// </summary>
        public static string Applicant_Hometown {
            get {
                return ResourceManager.GetString("Applicant_Hometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        public static string Applicant_IAgree {
            get {
                return ResourceManager.GetString("Applicant_IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal Work place.
        /// </summary>
        public static string Applicant_IdealWorkplace {
            get {
                return ResourceManager.GetString("Applicant_IdealWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityIsReplica.
        /// </summary>
        public static string Applicant_IdentityIsReplica {
            get {
                return ResourceManager.GetString("Applicant_IdentityIsReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityNo.
        /// </summary>
        public static string Applicant_IdentityNo {
            get {
                return ResourceManager.GetString("Applicant_IdentityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityReplicaReason.
        /// </summary>
        public static string Applicant_IdentityReplicaReason {
            get {
                return ResourceManager.GetString("Applicant_IdentityReplicaReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Applicant_JobTitle {
            get {
                return ResourceManager.GetString("Applicant_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageSkills.
        /// </summary>
        public static string Applicant_LanguageSkills {
            get {
                return ResourceManager.GetString("Applicant_LanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string Applicant_LastName {
            get {
                return ResourceManager.GetString("Applicant_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName in English.
        /// </summary>
        public static string Applicant_LastNameInEnglish {
            get {
                return ResourceManager.GetString("Applicant_LastNameInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaritalStatus.
        /// </summary>
        public static string Applicant_MaritalStatus {
            get {
                return ResourceManager.GetString("Applicant_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedicalSurgery.
        /// </summary>
        public static string Applicant_MedicalSurgery {
            get {
                return ResourceManager.GetString("Applicant_MedicalSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MilitaryServiceInfo.
        /// </summary>
        public static string Applicant_MilitaryServiceInfo {
            get {
                return ResourceManager.GetString("Applicant_MilitaryServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Status.
        /// </summary>
        public static string Applicant_MilitaryServiceStatus {
            get {
                return ResourceManager.GetString("Applicant_MilitaryServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNo.
        /// </summary>
        public static string Applicant_MobileNo {
            get {
                return ResourceManager.GetString("Applicant_MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Applicant_Nationality {
            get {
                return ResourceManager.GetString("Applicant_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalNo.
        /// </summary>
        public static string Applicant_NationalNo {
            get {
                return ResourceManager.GetString("Applicant_NationalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Applicant_Notes {
            get {
                return ResourceManager.GetString("Applicant_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherSkills.
        /// </summary>
        public static string Applicant_OtherSkills {
            get {
                return ResourceManager.GetString("Applicant_OtherSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OvertimeWork.
        /// </summary>
        public static string Applicant_OvertimeWork {
            get {
                return ResourceManager.GetString("Applicant_OvertimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OvertimeWork Hours.
        /// </summary>
        public static string Applicant_OvertimeWorkHours {
            get {
                return ResourceManager.GetString("Applicant_OvertimeWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportNo.
        /// </summary>
        public static string Applicant_PassportNo {
            get {
                return ResourceManager.GetString("Applicant_PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassportType.
        /// </summary>
        public static string Applicant_PassportType {
            get {
                return ResourceManager.GetString("Applicant_PassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermanentDrugUsage.
        /// </summary>
        public static string Applicant_PermanentDrugUsage {
            get {
                return ResourceManager.GetString("Applicant_PermanentDrugUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Applicant_Picture {
            get {
                return ResourceManager.GetString("Applicant_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousInterviews.
        /// </summary>
        public static string Applicant_PreviousInterviews {
            get {
                return ResourceManager.GetString("Applicant_PreviousInterviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        public static string Applicant_Publications {
            get {
                return ResourceManager.GetString("Applicant_Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string Applicant_References {
            get {
                return ResourceManager.GetString("Applicant_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelativeInCompany.
        /// </summary>
        public static string Applicant_RelativeInCompany {
            get {
                return ResourceManager.GetString("Applicant_RelativeInCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatives.
        /// </summary>
        public static string Applicant_Relatives {
            get {
                return ResourceManager.GetString("Applicant_Relatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Applicant_Religion {
            get {
                return ResourceManager.GetString("Applicant_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReligionSect.
        /// </summary>
        public static string Applicant_ReligionSect {
            get {
                return ResourceManager.GetString("Applicant_ReligionSect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondNationality.
        /// </summary>
        public static string Applicant_SecondNationality {
            get {
                return ResourceManager.GetString("Applicant_SecondNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Applicant_Skills {
            get {
                return ResourceManager.GetString("Applicant_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialSecurityInfo.
        /// </summary>
        public static string Applicant_SocialSecurityInfo {
            get {
                return ResourceManager.GetString("Applicant_SocialSecurityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialOrChronicDisease.
        /// </summary>
        public static string Applicant_SpecialOrChronicDisease {
            get {
                return ResourceManager.GetString("Applicant_SpecialOrChronicDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work TelNo.
        /// </summary>
        public static string Applicant_TelNo {
            get {
                return ResourceManager.GetString("Applicant_TelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Applicant_Weight {
            get {
                return ResourceManager.GetString("Applicant_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Available(Days).
        /// </summary>
        public static string Applicant_WhenAvailable {
            get {
                return ResourceManager.GetString("Applicant_WhenAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkExperienceInfos.
        /// </summary>
        public static string Applicant_WorkExperienceInfos {
            get {
                return ResourceManager.GetString("Applicant_WorkExperienceInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string Certificate_Date {
            get {
                return ResourceManager.GetString("Certificate_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Certificate_Duration {
            get {
                return ResourceManager.GetString("Certificate_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Certificate_Grade {
            get {
                return ResourceManager.GetString("Certificate_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you Have Documents?.
        /// </summary>
        public static string Certificate_HasDocument {
            get {
                return ResourceManager.GetString("Certificate_HasDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute.
        /// </summary>
        public static string Certificate_Institute {
            get {
                return ResourceManager.GetString("Certificate_Institute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Certificate_Location {
            get {
                return ResourceManager.GetString("Certificate_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Certificate_Title {
            get {
                return ResourceManager.GetString("Certificate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ChangePasswordModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string ChangePasswordModel_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string EducationInfo_College {
            get {
                return ResourceManager.GetString("EducationInfo_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string EducationInfo_Country {
            get {
                return ResourceManager.GetString("EducationInfo_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string EducationInfo_Finish {
            get {
                return ResourceManager.GetString("EducationInfo_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        public static string EducationInfo_GPA {
            get {
                return ResourceManager.GetString("EducationInfo_GPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string EducationInfo_Level {
            get {
                return ResourceManager.GetString("EducationInfo_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string EducationInfo_Major {
            get {
                return ResourceManager.GetString("EducationInfo_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string EducationInfo_Province {
            get {
                return ResourceManager.GetString("EducationInfo_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string EducationInfo_Start {
            get {
                return ResourceManager.GetString("EducationInfo_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Unit Type.
        /// </summary>
        public static string EducationInfo_TrainingUnitType {
            get {
                return ResourceManager.GetString("EducationInfo_TrainingUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor.
        /// </summary>
        public static string EducationLevel_Bachelor {
            get {
                return ResourceManager.GetString("EducationLevel_Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Year College.
        /// </summary>
        public static string EducationLevel_College {
            get {
                return ResourceManager.GetString("EducationLevel_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diploma.
        /// </summary>
        public static string EducationLevel_Diploma {
            get {
                return ResourceManager.GetString("EducationLevel_Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string EducationLevel_Master {
            get {
                return ResourceManager.GetString("EducationLevel_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string EducationLevel_None {
            get {
                return ResourceManager.GetString("EducationLevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhD.
        /// </summary>
        public static string EducationLevel_PhD {
            get {
                return ResourceManager.GetString("EducationLevel_PhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnderDiploma.
        /// </summary>
        public static string EducationLevel_UnderDiploma {
            get {
                return ResourceManager.GetString("EducationLevel_UnderDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Errand_City {
            get {
                return ResourceManager.GetString("Errand_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Errand_Country {
            get {
                return ResourceManager.GetString("Errand_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Errand_Finish {
            get {
                return ResourceManager.GetString("Errand_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Errand_Mission {
            get {
                return ResourceManager.GetString("Errand_Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Errand_Outcome {
            get {
                return ResourceManager.GetString("Errand_Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Errand_Role {
            get {
                return ResourceManager.GetString("Errand_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Errand_Start {
            get {
                return ResourceManager.GetString("Errand_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        public static string FamilyRelation_Brother {
            get {
                return ResourceManager.GetString("FamilyRelation_Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string FamilyRelation_Child {
            get {
                return ResourceManager.GetString("FamilyRelation_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple.
        /// </summary>
        public static string FamilyRelation_Couple {
            get {
                return ResourceManager.GetString("FamilyRelation_Couple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string FamilyRelation_Father {
            get {
                return ResourceManager.GetString("FamilyRelation_Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string FamilyRelation_Mother {
            get {
                return ResourceManager.GetString("FamilyRelation_Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        public static string FamilyRelation_Sister {
            get {
                return ResourceManager.GetString("FamilyRelation_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastQuarterTurnover.
        /// </summary>
        public static string FinancialInfo_LastQuarterTurnover {
            get {
                return ResourceManager.GetString("FinancialInfo_LastQuarterTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlySales.
        /// </summary>
        public static string FinancialInfo_MonthlySales {
            get {
                return ResourceManager.GetString("FinancialInfo_MonthlySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Gallery_AppearInHomePage {
            get {
                return ResourceManager.GetString("Gallery_AppearInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Gallery_Attachment {
            get {
                return ResourceManager.GetString("Gallery_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Date.
        /// </summary>
        public static string Gallery_CaptureDate {
            get {
                return ResourceManager.GetString("Gallery_CaptureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Gallery_Code {
            get {
                return ResourceManager.GetString("Gallery_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Gallery_Contents {
            get {
                return ResourceManager.GetString("Gallery_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Gallery_Image {
            get {
                return ResourceManager.GetString("Gallery_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string Gallery_PublishDate {
            get {
                return ResourceManager.GetString("Gallery_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Gallery_Published {
            get {
                return ResourceManager.GetString("Gallery_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Gallery_Title {
            get {
                return ResourceManager.GetString("Gallery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Gender_None {
            get {
                return ResourceManager.GetString("Gender_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string HabitaionType_None {
            get {
                return ResourceManager.GetString("HabitaionType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        public static string HabitaionType_Owned {
            get {
                return ResourceManager.GetString("HabitaionType_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        public static string HabitaionType_Rented {
            get {
                return ResourceManager.GetString("HabitaionType_Rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string HabitationInfo_Address {
            get {
                return ResourceManager.GetString("HabitationInfo_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string HabitationInfo_Finish {
            get {
                return ResourceManager.GetString("HabitationInfo_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HabitaionType.
        /// </summary>
        public static string HabitationInfo_HabitaionType {
            get {
                return ResourceManager.GetString("HabitationInfo_HabitaionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string HabitationInfo_Start {
            get {
                return ResourceManager.GetString("HabitationInfo_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string HabitationInfo_Zip {
            get {
                return ResourceManager.GetString("HabitationInfo_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        public static string JobCategory_Agriculture {
            get {
                return ResourceManager.GetString("JobCategory_Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial.
        /// </summary>
        public static string JobCategory_Commercial {
            get {
                return ResourceManager.GetString("JobCategory_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        public static string JobCategory_Government {
            get {
                return ResourceManager.GetString("JobCategory_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string JobCategory_Health {
            get {
                return ResourceManager.GetString("JobCategory_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string JobCategory_Industry {
            get {
                return ResourceManager.GetString("JobCategory_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string JobCategory_Other {
            get {
                return ResourceManager.GetString("JobCategory_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string JobCategory_Service {
            get {
                return ResourceManager.GetString("JobCategory_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string JobCategory_Training {
            get {
                return ResourceManager.GetString("JobCategory_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string JobPosition_Department {
            get {
                return ResourceManager.GetString("JobPosition_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobCode.
        /// </summary>
        public static string JobPosition_JobCode {
            get {
                return ResourceManager.GetString("JobPosition_JobCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobEducation.
        /// </summary>
        public static string JobPosition_JobEducation {
            get {
                return ResourceManager.GetString("JobPosition_JobEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobSkills.
        /// </summary>
        public static string JobPosition_JobSkills {
            get {
                return ResourceManager.GetString("JobPosition_JobSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle.
        /// </summary>
        public static string JobPosition_JobTitle {
            get {
                return ResourceManager.GetString("JobPosition_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobPosition_Xmlfile.
        /// </summary>
        public static string JobPosition_Xmlfile {
            get {
                return ResourceManager.GetString("JobPosition_Xmlfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehension.
        /// </summary>
        public static string LanguageSkill_Comprehension {
            get {
                return ResourceManager.GetString("LanguageSkill_Comprehension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageSkill_Language {
            get {
                return ResourceManager.GetString("LanguageSkill_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string LanguageSkill_Reading {
            get {
                return ResourceManager.GetString("LanguageSkill_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking.
        /// </summary>
        public static string LanguageSkill_Speaking {
            get {
                return ResourceManager.GetString("LanguageSkill_Speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string LanguageSkill_Writing {
            get {
                return ResourceManager.GetString("LanguageSkill_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Location_Province {
            get {
                return ResourceManager.GetString("Location_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogOnModel_Password {
            get {
                return ResourceManager.GetString("LogOnModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string LogOnModel_RememberMe {
            get {
                return ResourceManager.GetString("LogOnModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LogOnModel_UserName {
            get {
                return ResourceManager.GetString("LogOnModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string MaritalStatus_Married {
            get {
                return ResourceManager.GetString("MaritalStatus_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string MaritalStatus_None {
            get {
                return ResourceManager.GetString("MaritalStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string MaritalStatus_Other {
            get {
                return ResourceManager.GetString("MaritalStatus_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string MaritalStatus_Single {
            get {
                return ResourceManager.GetString("MaritalStatus_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNo.
        /// </summary>
        public static string MilitaryServiceInfo_CardNo {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempt.
        /// </summary>
        public static string MilitaryServiceInfo_Exempt {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_Exempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExemptReason.
        /// </summary>
        public static string MilitaryServiceInfo_ExemptReason {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_ExemptReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string MilitaryServiceInfo_Finish {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string MilitaryServiceInfo_Location {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MilitaryServiceInfo_Start {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MilitaryServiceInfo_Status {
            get {
                return ResourceManager.GetString("MilitaryServiceInfo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string MilitaryServiceStatus_Done {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempted.
        /// </summary>
        public static string MilitaryServiceStatus_Exempted {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus_Exempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string MilitaryServiceStatus_None {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Done.
        /// </summary>
        public static string MilitaryServiceStatus_NotDone {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus_NotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string MilitaryServiceStatus_Ongoing {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus_Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string News_AppearInHomePage {
            get {
                return ResourceManager.GetString("News_AppearInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string News_Attachment {
            get {
                return ResourceManager.GetString("News_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Date.
        /// </summary>
        public static string News_CaptureDate {
            get {
                return ResourceManager.GetString("News_CaptureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string News_Code {
            get {
                return ResourceManager.GetString("News_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string News_Contents {
            get {
                return ResourceManager.GetString("News_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string News_ExpirationDate {
            get {
                return ResourceManager.GetString("News_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string News_Image {
            get {
                return ResourceManager.GetString("News_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Language.
        /// </summary>
        public static string News_Language {
            get {
                return ResourceManager.GetString("News_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string News_PublishDate {
            get {
                return ResourceManager.GetString("News_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string News_Published {
            get {
                return ResourceManager.GetString("News_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string News_Title {
            get {
                return ResourceManager.GetString("News_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Publication_Date {
            get {
                return ResourceManager.GetString("Publication_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publication_Publisher {
            get {
                return ResourceManager.GetString("Publication_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Publication_Title {
            get {
                return ResourceManager.GetString("Publication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        public static string RegisterMember_Answer {
            get {
                return ResourceManager.GetString("RegisterMember_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterMember_ConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterMember_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterMember_Email {
            get {
                return ResourceManager.GetString("RegisterMember_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterMember_Password {
            get {
                return ResourceManager.GetString("RegisterMember_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        public static string RegisterMember_Question {
            get {
                return ResourceManager.GetString("RegisterMember_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string RegisterMember_UserName {
            get {
                return ResourceManager.GetString("RegisterMember_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string Relative_BirthDate {
            get {
                return ResourceManager.GetString("Relative_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel.
        /// </summary>
        public static string Relative_EducationLevel {
            get {
                return ResourceManager.GetString("Relative_EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string Relative_FirstName {
            get {
                return ResourceManager.GetString("Relative_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HabitationCity.
        /// </summary>
        public static string Relative_HabitationCity {
            get {
                return ResourceManager.GetString("Relative_HabitationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown.
        /// </summary>
        public static string Relative_Hometown {
            get {
                return ResourceManager.GetString("Relative_Hometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string Relative_LastName {
            get {
                return ResourceManager.GetString("Relative_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Relative_Relation {
            get {
                return ResourceManager.GetString("Relative_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        public static string Relative_Workplace {
            get {
                return ResourceManager.GetString("Relative_Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkPosition.
        /// </summary>
        public static string Relative_WorkPosition {
            get {
                return ResourceManager.GetString("Relative_WorkPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ServiceType_Data {
            get {
                return ResourceManager.GetString("ServiceType_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartphone.
        /// </summary>
        public static string ServiceType_Smartphone {
            get {
                return ResourceManager.GetString("ServiceType_Smartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string SimType_Data {
            get {
                return ResourceManager.GetString("SimType_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        public static string SimType_None {
            get {
                return ResourceManager.GetString("SimType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpaid.
        /// </summary>
        public static string SimType_Postpaid {
            get {
                return ResourceManager.GetString("SimType_Postpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid.
        /// </summary>
        public static string SimType_Prepaid {
            get {
                return ResourceManager.GetString("SimType_Prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Skill_Level {
            get {
                return ResourceManager.GetString("Skill_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleUsage.
        /// </summary>
        public static string Skill_SampleUsage {
            get {
                return ResourceManager.GetString("Skill_SampleUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Skill_Title {
            get {
                return ResourceManager.GetString("Skill_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string SkillLevel_Average {
            get {
                return ResourceManager.GetString("SkillLevel_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string SkillLevel_Good {
            get {
                return ResourceManager.GetString("SkillLevel_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        public static string SkillLevel_Perfect {
            get {
                return ResourceManager.GetString("SkillLevel_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string SkillLevel_Poor {
            get {
                return ResourceManager.GetString("SkillLevel_Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string SocialSecurityInfo_Duration {
            get {
                return ResourceManager.GetString("SocialSecurityInfo_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        public static string SocialSecurityInfo_Has {
            get {
                return ResourceManager.GetString("SocialSecurityInfo_Has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OthersDuration.
        /// </summary>
        public static string SocialSecurityInfo_OthersDuration {
            get {
                return ResourceManager.GetString("SocialSecurityInfo_OthersDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SocialSecurityInfo_Type {
            get {
                return ResourceManager.GetString("SocialSecurityInfo_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts Volume.
        /// </summary>
        public static string SpecializedServiceInfo_ContractsVolume {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_ContractsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string SpecializedServiceInfo_Customers {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string SpecializedServiceInfo_Field {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Volume.
        /// </summary>
        public static string SpecializedServiceInfo_FinancialVolume {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_FinancialVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed projects.
        /// </summary>
        public static string SpecializedServiceInfo_Passedprojects {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_Passedprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec Equipment.
        /// </summary>
        public static string SpecializedServiceInfo_SpecEquipment {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_SpecEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff No..
        /// </summary>
        public static string SpecializedServiceInfo_StaffNo {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_StaffNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string SpecializedServiceInfo_Topic {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Approvals.
        /// </summary>
        public static string SpecializedServiceInfo_ValidApprovals {
            get {
                return ResourceManager.GetString("SpecializedServiceInfo_ValidApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Maker.
        /// </summary>
        public static string StaffInfo_DecisionMaker {
            get {
                return ResourceManager.GetString("StaffInfo_DecisionMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string StaffInfo_Email {
            get {
                return ResourceManager.GetString("StaffInfo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string StaffInfo_FirstName {
            get {
                return ResourceManager.GetString("StaffInfo_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string StaffInfo_LastName {
            get {
                return ResourceManager.GetString("StaffInfo_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string StaffInfo_Level {
            get {
                return ResourceManager.GetString("StaffInfo_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNo.
        /// </summary>
        public static string StaffInfo_MobileNo {
            get {
                return ResourceManager.GetString("StaffInfo_MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string StaffInfo_Post {
            get {
                return ResourceManager.GetString("StaffInfo_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelAreaCode.
        /// </summary>
        public static string StaffInfo_TelAreaCode {
            get {
                return ResourceManager.GetString("StaffInfo_TelAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelNo.
        /// </summary>
        public static string StaffInfo_TelNo {
            get {
                return ResourceManager.GetString("StaffInfo_TelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveVehicle.
        /// </summary>
        public static string StoreHouseInfo_ActiveVehicle {
            get {
                return ResourceManager.GetString("StoreHouseInfo_ActiveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSize.
        /// </summary>
        public static string StoreHouseInfo_TotalSize {
            get {
                return ResourceManager.GetString("StoreHouseInfo_TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalStaff.
        /// </summary>
        public static string StoreHouseInfo_TotalStaff {
            get {
                return ResourceManager.GetString("StoreHouseInfo_TotalStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Free
        ///    .
        /// </summary>
        public static string TrainingUnitType_Free {
            get {
                return ResourceManager.GetString("TrainingUnitType_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Non Profit
        ///    .
        /// </summary>
        public static string TrainingUnitType_NonProfit {
            get {
                return ResourceManager.GetString("TrainingUnitType_NonProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Other
        ///    .
        /// </summary>
        public static string TrainingUnitType_Other {
            get {
                return ResourceManager.GetString("TrainingUnitType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      PayamNoor
        ///    .
        /// </summary>
        public static string TrainingUnitType_PayamNoor {
            get {
                return ResourceManager.GetString("TrainingUnitType_PayamNoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      State
        ///    .
        /// </summary>
        public static string TrainingUnitType_State {
            get {
                return ResourceManager.GetString("TrainingUnitType_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string VehicleInfo_Count {
            get {
                return ResourceManager.GetString("VehicleInfo_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string VehicleInfo_Type {
            get {
                return ResourceManager.GetString("VehicleInfo_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string WorkExperienceInfo_Address {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string WorkExperienceInfo_Company {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractType.
        /// </summary>
        public static string WorkExperienceInfo_ContractType {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string WorkExperienceInfo_Finish {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string WorkExperienceInfo_Industry {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        public static string WorkExperienceInfo_JobDescription {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string WorkExperienceInfo_Position {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuitReason.
        /// </summary>
        public static string WorkExperienceInfo_QuitReason {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_QuitReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Per Month.
        /// </summary>
        public static string WorkExperienceInfo_Salary {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string WorkExperienceInfo_Start {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suboridnates.
        /// </summary>
        public static string WorkExperienceInfo_Suboridnates {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_Suboridnates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelNo.
        /// </summary>
        public static string WorkExperienceInfo_TelNo {
            get {
                return ResourceManager.GetString("WorkExperienceInfo_TelNo", resourceCulture);
            }
        }
    }
}
