//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedar.WebPortal.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlossaryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlossaryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cedar.WebPortal.Domain.Resources.GlossaryResource", typeof(GlossaryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Persmissions.
        /// </summary>
        public static string Accessible_Persmissions {
            get {
                return ResourceManager.GetString("Accessible_Persmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alborz.
        /// </summary>
        public static string Alborz {
            get {
                return ResourceManager.GetString("Alborz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice .
        /// </summary>
        public static string Applicant_Dialog_Message {
            get {
                return ResourceManager.GetString("Applicant_Dialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a EnglishCV is required.
        /// </summary>
        public static string Applicant_EnglishCV {
            get {
                return ResourceManager.GetString("Applicant_EnglishCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;p&gt;
        ///			In order to run the 3rd Telecom Operator, 
        ///			We need eligble persons based on this priorities:
        ///			&lt;ul&gt;
        ///			Qualification :
        ///			&lt;li&gt;
        ///			1. Men with military obligation service pass 
        ///				 or Exempt Card(not medical )
        ///			&lt;/li&gt;&lt;li&gt;
        ///			2. Mental and Phydical Health
        ///			&lt;/li&gt;&lt;li&gt;
        ///			3- No Criminal Record
        ///			&lt;/li&gt;
        ///			&lt;/p&gt;
        ///			.
        /// </summary>
        public static string Applicant_IntroMessage {
            get {
                return ResourceManager.GetString("Applicant_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1.
        /// </summary>
        public static string Applicant_Part1 {
            get {
                return ResourceManager.GetString("Applicant_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2.
        /// </summary>
        public static string Applicant_Part2 {
            get {
                return ResourceManager.GetString("Applicant_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3.
        /// </summary>
        public static string Applicant_Part3 {
            get {
                return ResourceManager.GetString("Applicant_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 4.
        /// </summary>
        public static string Applicant_Part4 {
            get {
                return ResourceManager.GetString("Applicant_Part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registeration is done.
        /// </summary>
        public static string Applicant_Success_Message {
            get {
                return ResourceManager.GetString("Applicant_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    SectionB
        ///    .
        /// </summary>
        public static string ApplicantSalesShop_SectionB {
            get {
                return ResourceManager.GetString("ApplicantSalesShop_SectionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   
        ///		&lt;p&gt;
        ///		Please send files less than 20 MB.
        ///		The old file will be replaced by new one.
        ///		&lt;/p&gt;
        ///	
        ///		.
        /// </summary>
        public static string AttachmentUploadMessage {
            get {
                return ResourceManager.GetString("AttachmentUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cedar.
        /// </summary>
        public static string Cedar {
            get {
                return ResourceManager.GetString("Cedar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamin Telecom News.
        /// </summary>
        public static string CedarNews {
            get {
                return ResourceManager.GetString("CedarNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contact Point Details.
        /// </summary>
        public static string Company_ContactPointHeaderDesc {
            get {
                return ResourceManager.GetString("Company_ContactPointHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current and Relevant Projects.
        /// </summary>
        public static string Company_CurrentProjects {
            get {
                return ResourceManager.GetString("Company_CurrentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may upload the Documents Related to Equipment Production Section From Here.
        /// </summary>
        public static string Company_FileUploadDescription {
            get {
                return ResourceManager.GetString("Company_FileUploadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        public static string Company_ProductList {
            get {
                return ResourceManager.GetString("Company_ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProPosal For Producting New Products.
        /// </summary>
        public static string Company_ProposalForProduct {
            get {
                return ResourceManager.GetString("Company_ProposalForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Area.
        /// </summary>
        public static string CompanyArea {
            get {
                return ResourceManager.GetString("CompanyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2011 XYZ. All rights reserved.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string CreateAndNextStep {
            get {
                return ResourceManager.GetString("CreateAndNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string EnterUsernamePasswordMessage {
            get {
                return ResourceManager.GetString("EnterUsernamePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///     &lt;h2&gt;  Our apologies…&lt;/h2&gt;
        ///&lt;p&gt;The page you requested cannot be displayed&lt;/p&gt;
        ///&lt;div&gt;
        ///&lt;ul &gt;
        ///&lt;li&gt;If you typed the address, make sure the spelling is correct.&lt;br /&gt;
        ///Note: Most addresses are also case sensitive.&lt;/li&gt;
        ///&lt;li&gt;If you clicked on a link, there may be a problem with that link. You can use &quot;Get assistance&quot; below.&lt;/li&gt;
        ///&lt;li&gt;For information on Cedar offerings, start from the &lt;a href=&quot;http://www.Cedar.ir/&quot;&gt;Cedar homepage&lt;/a&gt;.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///&lt;h2&gt;Get assistance&lt;/h2&gt;&lt;/div&gt;
        ///&lt;div  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attachments.
        /// </summary>
        public static string FileAttach {
            get {
                return ResourceManager.GetString("FileAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAgree.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      &lt;strong &gt;3G Mobile&lt;/strong&gt;&lt;p&gt;
        ///        &lt;br /&gt;
        ///       3G or 3rd generation mobile telecommunications is a generation of standards for mobile phones and mobile telecommunication services fulfilling the International Mobile Telecommunications-2000 (IMT-2000) specifications by the International Telecommunication Union.
        ///      &lt;/p&gt; .
        /// </summary>
        public static string Intro_3G {
            get {
                return ResourceManager.GetString("Intro_3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LogonErrorMessage {
            get {
                return ResourceManager.GetString("LogonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Area.
        /// </summary>
        public static string MembershipArea {
            get {
                return ResourceManager.GetString("MembershipArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was successful.
        /// </summary>
        public static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Headlines.
        /// </summary>
        public static string News_Headlines {
            get {
                return ResourceManager.GetString("News_Headlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next:.
        /// </summary>
        public static string News_Next {
            get {
                return ResourceManager.GetString("News_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No:.
        /// </summary>
        public static string News_No {
            get {
                return ResourceManager.GetString("News_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous:.
        /// </summary>
        public static string News_Previous {
            get {
                return ResourceManager.GetString("News_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He does not select any job position.
        /// </summary>
        public static string NoJobPosition {
            get {
                return ResourceManager.GetString("NoJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration .
        /// </summary>
        public static string RegisterMember {
            get {
                return ResourceManager.GetString("RegisterMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To List.
        /// </summary>
        public static string ReturnToList {
            get {
                return ResourceManager.GetString("ReturnToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Search for job position
        ///    .
        /// </summary>
        public static string SearchJobPosition {
            get {
                return ResourceManager.GetString("SearchJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehran.
        /// </summary>
        public static string Tehran {
            get {
                return ResourceManager.GetString("Tehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your file is being uploaded.
        /// </summary>
        public static string UploadMessage {
            get {
                return ResourceManager.GetString("UploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether.
        /// </summary>
        public static string Wheather {
            get {
                return ResourceManager.GetString("Wheather", resourceCulture);
            }
        }
    }
}
