EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'Cedar'
GO
USE [master]
GO
ALTER DATABASE [Cedar] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO

/****** Object:  Database [Cedar]    Script Date: 09/25/2011 02:27:13 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'Cedar')
DROP DATABASE [Cedar]
GO

USE [master]
GO

/****** Object:  Database [Cedar]    Script Date: 09/25/2011 02:27:13 ******/
CREATE DATABASE [Cedar] ON  PRIMARY 
( NAME = N'Cedar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Cedar1.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cedar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Cedar1_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Cedar] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cedar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cedar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cedar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cedar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cedar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cedar] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cedar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cedar] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Cedar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cedar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cedar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cedar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cedar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cedar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cedar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cedar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cedar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cedar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cedar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cedar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cedar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cedar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cedar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cedar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cedar] SET  READ_WRITE 
GO

ALTER DATABASE [Cedar] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Cedar] SET  MULTI_USER 
GO

ALTER DATABASE [Cedar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cedar] SET DB_CHAINING OFF 
GO


